<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPrt0wvj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPrt0wvj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPrt0wvj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPrt0wvj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPrt0wvj\appProdProjectContainer([
    'container.build_hash' => 'Prt0wvj',
    'container.build_id' => 'b3e1ea76',
    'container.build_time' => 1600990769,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPrt0wvj');
